[pytest]

# Permite imports tipo backend.*
pythonpath = .

# Solo buscar tests en estas carpetas
testpaths =
    backend/api
    backend/observatory

# patrones válidos de archivos
python_files =
    test_*.py

# clases de test
python_classes =
    Test*

# funciones de test
python_functions =
    test_*

# opciones de ejecución
addopts =
    -ra
    --tb=short
    --strict-markers

# carpetas que pytest NO debe escanear
norecursedirs =
    .venv
    venv
    env
    build
    dist
    node_modules
    app_mobile
    .git
    __pycache__
    android
    ios
    docs